cxl tool: generate cxl tool repo by decouping cxl from ndctl repo
all changes are listed in CHANGES

diff --git a/scripts/do_abidiff b/scripts/do_abidiff
--- a/scripts/do_abidiff
+++ b/scripts/do_abidiff
@@ -16,31 +16,31 @@ build_rpm()
 	local ref="$1"
 	local version=""
 
-	# prepare ndctl tree
-	rm -rf results_ndctl
+	# prepare cxl-tool tree
+	rm -rf results_cxl-tool
 	git checkout -b rel_${ref} $ref
 	./autogen.sh
 	./configure CFLAGS='-g -O2' --prefix=/usr --sysconfdir=/etc --libdir=/usr/lib64
 	make clean
-	make rhel/ndctl.spec
-	cp rhel/ndctl.spec .
+	make rhel/cxl-tool.spec
+	cp rhel/cxl-tool.spec .
 
 	# build and copy RPMs
 	version="$(./git-version)"
 	release="f$(basename $(readlink -f /etc/mock/default.cfg) | cut -d- -f2)"
-	git archive  --format=tar --prefix="ndctl-${version}/" HEAD | gzip > ndctl-${version}.tar.gz
-	fedpkg --release $release --name=ndctl mockbuild
+	git archive  --format=tar --prefix="cxl-tool-${version}/" HEAD | gzip > cxl-tool-${version}.tar.gz
+	fedpkg --release $release --name=cxl-tool mockbuild
 	[ "$?" -eq 0 ] || err "error building $ref"
 	mkdir -p release/rel_${ref}/
-	cp results_ndctl/*/*/*.x86_64.rpm release/rel_${ref}/
+	cp results_cxl-tool/*/*/*.x86_64.rpm release/rel_${ref}/
 
-	# restore ndctl branch and cleanup
+	# restore cxl-tool branch and cleanup
 	git checkout $cur
 	git branch -D rel_${ref}
-	rm ndctl-${version}.tar.gz
-	rm ndctl-${version}*.src.rpm
-	rm -rf results_ndctl
-	rm -f ndctl.spec
+	rm cxl-tool-${version}.tar.gz
+	rm cxl-tool-${version}*.src.rpm
+	rm -rf results_cxl-tool
+	rm -f cxl-tool.spec
 }
 
 do_diff()
@@ -53,7 +53,7 @@ do_diff()
 	local old_lib="$(find . -regex "./release/rel_${old}/${pkg}-libs-[0-9]+.*" | head -1)"
 	local new_lib="$(find . -regex "./release/rel_${new}/${pkg}-libs-[0-9]+.*" | head -1)"
 
-	[ -n "$pkg" ] || err "specify a package for diff (ndctl, daxctl, cxl)"
+	[ -n "$pkg" ] || err "specify a package for diff cxl"
 	[ -n "$old_base" ] || err "$pkg: old_base empty, possible build failure"
 	[ -n "$new_base" ] || err "$pkg: new_base empty, possible build failure"
 
@@ -65,7 +65,7 @@ do_diff()
 		"$old_lib" "$new_lib"
 }
 
-[ -e "COPYING" ] || err "Run from the top level of an ndctl tree"
+[ -e "COPYING" ] || err "Run from the top level of an cxl-tool tree"
 if ! command -v "abipkgdiff" >/dev/null; then
 	err "missing abipkgdiff. Please install libabigail"
 fi
@@ -73,6 +73,4 @@ rm -rf release/rel*
 
 build_rpm $old > release/buildlog_$old 2>&1
 build_rpm $new > release/buildlog_$new 2>&1
-do_diff ndctl
-do_diff daxctl
 do_diff cxl
